#!/bin/bash
cd ~/osmocom-bb-identity/src/host/osmocon
./osmocon -p /dev/ttyUSB1 -s /tmp/osmocom_l2_1 -m c140xor -c ../../target/firmware/board/se_j100/layer1.highram.bin ../../target/firmware/board/se_j100/chainload.compalram.bin
